#!/usr/bin/env bash
#
# Idempotent Cloud Agent bootstrap for Apache Lucene.
#
# Lucene's main branch requires JDK 25 (gradle/libs.versions.toml: minJava=25),
# while the default Cloud Agent base image ships an older JDK. This script:
#   1. installs a pinned Eclipse Temurin JDK 25 (checksum verified),
#   2. makes it the default `java`/`javac` and the JVM Gradle runs on, and
#   3. warms the Gradle wrapper + dependency caches by assembling lucene-core.
#
# It is safe to run repeatedly: each step is guarded and converges.
set -euo pipefail

JDK_URL="https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4.1%2B1/OpenJDK25U-jdk_x64_linux_hotspot_25.0.4.1_1.tar.gz"
JDK_SHA256="dbb698396d478e7fa2b1e50f4103324b2a99b90569ee27c33f2261f9215cf41e"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

# Prefer a system-wide location when we can write it; otherwise fall back to the
# user's home so the script also works without sudo.
if sudo -n true 2>/dev/null; then
  SUDO="sudo"
  JAVA_HOME="/opt/jdk25"
else
  SUDO=""
  JAVA_HOME="${HOME}/.local/lib/jdk25"
fi
export JAVA_HOME

jdk_ok() {
  [ -x "${JAVA_HOME}/bin/java" ] && "${JAVA_HOME}/bin/java" -version 2>&1 | grep -q '"25'
}

if jdk_ok; then
  echo "JDK 25 already installed at ${JAVA_HOME}"
else
  echo "Installing Eclipse Temurin JDK 25 to ${JAVA_HOME} ..."
  tmp="$(mktemp -d)"
  curl -fsSL -o "${tmp}/jdk.tar.gz" "${JDK_URL}"
  echo "${JDK_SHA256}  ${tmp}/jdk.tar.gz" | sha256sum -c -
  ${SUDO} rm -rf "${JAVA_HOME}"
  ${SUDO} mkdir -p "${JAVA_HOME}"
  ${SUDO} tar -xzf "${tmp}/jdk.tar.gz" -C "${JAVA_HOME}" --strip-components=1
  rm -rf "${tmp}"
fi

export PATH="${JAVA_HOME}/bin:${PATH}"

# Make JDK 25 the default `java`/`javac`/`jshell`/`jar` for all interactive
# shells. /usr/local/bin precedes /usr/bin on PATH, so these symlinks win.
if [ -n "${SUDO}" ]; then
  for tool in java javac jshell jar keytool; do
    if [ -x "${JAVA_HOME}/bin/${tool}" ]; then
      ${SUDO} ln -sf "${JAVA_HOME}/bin/${tool}" "/usr/local/bin/${tool}"
    fi
  done
fi

# Ensure every Gradle invocation runs on JDK 25 regardless of the caller's PATH.
# The project-local gradle.properties (generated by gradlew) does not set this,
# so a user-level value takes effect and persists in the environment snapshot.
mkdir -p "${HOME}/.gradle"
user_props="${HOME}/.gradle/gradle.properties"
touch "${user_props}"
sed -i '/^org\.gradle\.java\.home=/d' "${user_props}"
echo "org.gradle.java.home=${JAVA_HOME}" >> "${user_props}"

echo "== Toolchain =="
java -version
./gradlew --version

echo "== Warming Gradle caches (assembling lucene-core) =="
./gradlew :lucene:core:assemble
